services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=monolithic'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=sa'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
