server:
  port: ${SERVER_PORT:81}

spring:
  application:
    name: monolithic
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/monolithic}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/monolithic}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    persist-authorization: true
    display-request-duration: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:change-this-secret-key-to-at-least-32-bytes}
    access-token-expiration-seconds: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:86400}
    refresh-token-expiration-seconds: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:2592000}
