server:
  port: 81

spring:
  application:
    name: monolithic
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_only
  datasource:
    url: jdbc:postgresql://localhost:5432/monolithic
    username: sa
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    persist-authorization: true
    display-request-duration: true
    custom-js-url: /swagger-custom.js

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

security:
  jwt:
    secret: change-this-secret-key-to-at-least-32-bytes
    access-token-expiration-seconds: 86400
    refresh-token-expiration-seconds: 2592000
