CREATE TABLE T_USER (
    ID                  VARCHAR(36) NOT NULL PRIMARY KEY,
    EMAIL               VARCHAR(255) NOT NULL,
    USR                 VARCHAR(255) NOT NULL,
    PWD                 VARCHAR(255) NOT NULL,
    STATE               VARCHAR(255) NOT NULL DEFAULT 'ACTIVE'
);

ALTER TABLE T_USER
    ADD CONSTRAINT UQ_USERNAME UNIQUE (USR),
    ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL);

INSERT INTO T_USER VALUES
    ('3cffc85f-97b3-48c2-8396-3f6963c2c4e3', 'nguyenthtri22095@gmail.com', 'administrator', '$2y$10$ONzjK8BwmqDqUXXXi9lnQOcYdvi/B/H7LN4Y2I85008JHErAvcvkG', 'ACTIVE');

CREATE TABLE T_USER_INFO (
    USER_ID             VARCHAR(36) NOT NULL PRIMARY KEY,
    FULL_NAME           VARCHAR(255),
    DOB                 DATE,
    PERMANENT_ADDRESS   VARCHAR(255),
    TEMPORARY_ADDRESS   VARCHAR(255),
    PHONE               VARCHAR(255),
    GENDER              VARCHAR(255),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(ID)
);

INSERT INTO T_USER_INFO VALUES
    ('3cffc85f-97b3-48c2-8396-3f6963c2c4e3', 'Tri Nguyen', NULL, NULL, NULL, NULL, 'MALE');

CREATE TABLE T_ROLE (
    ROLE                VARCHAR(255) NOT NULL PRIMARY KEY,
    DESCRIPTION         VARCHAR(512),
    STATE               VARCHAR(255) NOT NULL DEFAULT 'ACTIVE'
);

INSERT INTO T_ROLE VALUES
    ('Administrator', NULL, 'ACTIVE'),
    ('User', NULL, 'ACTIVE');

CREATE TABLE T_PERMISSION (
    PERMISSION          VARCHAR(255) NOT NULL PRIMARY KEY,
    DESCRIPTION         VARCHAR(512),
    STATE               VARCHAR(255) NOT NULL DEFAULT 'ACTIVE'
);

INSERT INTO T_PERMISSION VALUES
    ('Read', NULL, 'ACTIVE'),
    ('Write', NULL, 'ACTIVE');

CREATE TABLE T_USER_ROLE (
    USER_ID         VARCHAR(36),
    ROLE            VARCHAR(255),
    CONSTRAINT UQ_USER_ROLE UNIQUE (USER_ID, ROLE),
    CONSTRAINT FK_WITH_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(ID),
    CONSTRAINT FK_WITH_ROLE FOREIGN KEY (ROLE) REFERENCES T_ROLE(ROLE)
);

INSERT INTO T_USER_ROLE VALUES
    ('3cffc85f-97b3-48c2-8396-3f6963c2c4e3', 'Administrator'),
    ('3cffc85f-97b3-48c2-8396-3f6963c2c4e3', 'User');

CREATE TABLE ROLE_PERMISSION (
    PERMISSION      VARCHAR(255),
    ROLE            VARCHAR(255),
    CONSTRAINT UQ_ROLE_PERMISSION UNIQUE (PERMISSION, ROLE),
    CONSTRAINT FK_WITH_ROLE_FROM_PERMISISON FOREIGN KEY (ROLE) REFERENCES T_ROLE(ROLE),
    CONSTRAINT FK_WITH_PERMISSION FOREIGN KEY (PERMISSION) REFERENCES T_PERMISSION(PERMISSION)
);

INSERT INTO ROLE_PERMISSION VALUES
    ('Read', 'Administrator'),
    ('Write', 'Administrator'),
    ('Read', 'User');
